title: Normal Zero의 기술 블로그
description: Normal Zero는 프로그래밍을 하면서 코드리뷰를 하는 블로그 입니다.

url: https://normalzero.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: normalzero
  email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
